CREATE DATABASE IF NOT EXISTS A04_Gaming;
USE A04_Gaming;

CREATE TABLE players (
    player_id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(100) NOT NULL UNIQUE,
    country_code CHAR(2), -- 'US', 'UA', 'PL'
    registration_date DATE NOT NULL
) ENGINE=InnoDB;

CREATE TABLE matches (
    match_id BIGINT AUTO_INCREMENT PRIMARY KEY,
    game_mode VARCHAR(50) NOT NULL,
    map_name VARCHAR(100) NOT NULL,
    match_start TIMESTAMP NOT NULL,
    match_duration_seconds INT NOT NULL
) ENGINE=InnoDB;
CREATE TABLE match_results (
    result_id BIGINT AUTO_INCREMENT PRIMARY KEY,
    match_id BIGINT NOT NULL,
    player_id INT NOT NULL,
    team ENUM('Red', 'Blue') NOT NULL,
    kills SMALLINT DEFAULT 0,
    deaths SMALLINT DEFAULT 0,
    score INT DEFAULT 0,
	CONSTRAINT fk_result_match
        FOREIGN KEY (match_id) 
        REFERENCES matches(match_id),
    
    CONSTRAINT fk_result_player
        FOREIGN KEY (player_id) 
        REFERENCES players(player_id),
        
    INDEX idx_match_id (match_id),
    INDEX idx_player_id (player_id)
) ENGINE=InnoDB;
-- Joining of the tables
SELECT *
FROM
    match_results AS mr
JOIN players AS p ON mr.player_id = p.player_id
JOIN matches AS m ON mr.match_id = m.match_id
LIMIT 10;
-- Query generated by AI
SELECT p.username, SUM(mr.score) AS total_score,
    (
        SELECT COUNT(*)
        FROM match_results AS mr_inner
        JOIN matches AS m_inner ON mr_inner.match_id = m_inner.match_id
        WHERE mr_inner.player_id = p.player_id AND m_inner.map_name = 'Dust2'
    ) AS dust2_match_count
FROM players AS p
JOIN match_results AS mr ON p.player_id = mr.player_id
WHERE LEFT(p.country_code, 2) = 'UA'
GROUP BY p.player_id, p.username
ORDER BY total_score DESC;

-- Optimized query
CREATE INDEX idx_player_country ON players(country_code);
CREATE INDEX idx_match_map ON matches(map_name);
CREATE INDEX idx_mr_player_score ON match_results(player_id, score);
SELECT p.username, SUM(mr.score) AS total_score, SUM(CASE WHEN m.map_name = 'Dust2' THEN 1 ELSE 0 END) AS dust2_match_count
FROM players AS p
JOIN match_results AS mr ON p.player_id = mr.player_id
JOIN matches AS m ON mr.match_id = m.match_id
WHERE p.country_code = 'UA'
GROUP BY p.player_id, p.username
ORDER BY total_score DESC;